# Generated by Django 4.2.24 on 2025-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_subscriptionplan_usagerecord_twofactorsession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_users",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
