# Generated by Django 4.2.24 on 2025-09-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0004_subscription_approval_notes_subscription_approved_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="stripe_invoice_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="stripe_payment_method_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("tenant", "stripe_invoice_id")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("tenant", "stripe_payment_method_id")},
        ),
    ]
