# Generated by Django 4.2.24 on 2025-09-26 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_initial"),
        ("products", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_lines",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_lines",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_lines",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="orderfulfillmentline",
            name="fulfillment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fulfillment_lines",
                to="orders.orderfulfillment",
            ),
        ),
        migrations.AddField(
            model_name="orderfulfillmentline",
            name="order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fulfillment_lines",
                to="orders.orderline",
            ),
        ),
        migrations.AddField(
            model_name="orderfulfillmentline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="orderfulfillment",
            name="fulfilled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderfulfillment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fulfillments",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderfulfillment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="orderfulfillment",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fulfillments",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="products.supplier",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderfulfillmentline",
            unique_together={("fulfillment", "order_line")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_type", "status"], name="orders_order_t_4558a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_date"], name="orders_order_d_6e39a9_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status"], name="orders_payment_050188_idx"
            ),
        ),
    ]
