# Generated by Django 4.2.24 on 2025-09-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_fix_order_number_tenant_isolation"),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("tenant", "order_number")},
        ),
    ]
