# Generated by Django 4.2.24 on 2025-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0004_subscription_approval_notes_subscription_approved_at_and_more",
        ),
        ("products", "0003_remove_sku_unique_constraint"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("tenant", "sku")},
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("tenant", "barcode"), ("tenant", "sku")},
        ),
    ]
