# Generated by Django 4.2.24 on 2025-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
