# Generated by Django 4.2.24 on 2025-09-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="woocommercestore",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="shopifystore",
            name="integration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopify_store",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="shopifystore",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="integrationwebhook",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="integrationwebhook",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="integrationsync",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="syncs",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="integrationsync",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="integrationmapping",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mappings",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="integrationmapping",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="integrationlog",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="integrationlog",
            name="sync",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="integrations.integrationsync",
            ),
        ),
        migrations.AddField(
            model_name="integrationlog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="integrationlog",
            name="webhook",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="integrations.integrationwebhook",
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationwebhook",
            index=models.Index(
                fields=["integration", "status"], name="integration_integra_9aee78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationwebhook",
            index=models.Index(
                fields=["event_type", "status"], name="integration_event_t_f0c4b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integrationmapping",
            unique_together={("integration", "mapping_type", "local_field")},
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(
                fields=["integration", "level"], name="integration_integra_9d6877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(
                fields=["created_at"], name="integration_created_b8d84c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integration",
            unique_together={("tenant", "integration_type")},
        ),
    ]
